server.port=${SERVER_PORT:3000}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost/lucidstack}
spring.data.mongodb.auto-index-creation=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION:true}
lucidstack.jwt.secret.key=${LUCIDSTACK_JWT_SECRET_KEY:jwt.secret.jwt.secret.jwt.secret.jwt.secret.jwt.secret.jwt.secret}